/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as InfoSlugRouteImport } from './routes/info/$slug'
import { Route as ListYourVenueIndexRouteImport } from './routes/list-your-venue/index'
import { Route as SigninIndexRouteImport } from './routes/signin/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as VenuesIndexRouteImport } from './routes/venues/index'
import { Route as AccountBookingsIndexRouteImport } from './routes/account/bookings/index'
import { Route as AccountSavedIndexRouteImport } from './routes/account/saved/index'
import { Route as VenuesVenueIdIndexRouteImport } from './routes/venues/$venueId/index'
import { Route as VenuesVenueIdBookRouteImport } from './routes/venues/$venueId/book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSlugRoute = InfoSlugRouteImport.update({
  id: '/info/$slug',
  path: '/info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourVenueIndexRoute = ListYourVenueIndexRouteImport.update({
  id: '/list-your-venue/',
  path: '/list-your-venue/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsIndexRoute = AccountBookingsIndexRouteImport.update({
  id: '/account/bookings/',
  path: '/account/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSavedIndexRoute = AccountSavedIndexRouteImport.update({
  id: '/account/saved/',
  path: '/account/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdIndexRoute = VenuesVenueIdIndexRouteImport.update({
  id: '/venues/$venueId/',
  path: '/venues/$venueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdBookRoute = VenuesVenueIdBookRouteImport.update({
  id: '/venues/$venueId/book',
  path: '/venues/$venueId/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/info/$slug': typeof InfoSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/list-your-venue/': typeof ListYourVenueIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/venues/$venueId/book': typeof VenuesVenueIdBookRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/account/saved/': typeof AccountSavedIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/info/$slug': typeof InfoSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/list-your-venue': typeof ListYourVenueIndexRoute
  '/signin': typeof SigninIndexRoute
  '/signup': typeof SignupIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/venues/$venueId/book': typeof VenuesVenueIdBookRoute
  '/account/bookings': typeof AccountBookingsIndexRoute
  '/account/saved': typeof AccountSavedIndexRoute
  '/venues/$venueId': typeof VenuesVenueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/info/$slug': typeof InfoSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/list-your-venue/': typeof ListYourVenueIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/venues/$venueId/book': typeof VenuesVenueIdBookRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/account/saved/': typeof AccountSavedIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$collectionId'
    | '/info/$slug'
    | '/collections/'
    | '/list-your-venue/'
    | '/signin/'
    | '/signup/'
    | '/venues/'
    | '/venues/$venueId/book'
    | '/account/bookings/'
    | '/account/saved/'
    | '/venues/$venueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/$collectionId'
    | '/info/$slug'
    | '/collections'
    | '/list-your-venue'
    | '/signin'
    | '/signup'
    | '/venues'
    | '/venues/$venueId/book'
    | '/account/bookings'
    | '/account/saved'
    | '/venues/$venueId'
  id:
    | '__root__'
    | '/'
    | '/collections/$collectionId'
    | '/info/$slug'
    | '/collections/'
    | '/list-your-venue/'
    | '/signin/'
    | '/signup/'
    | '/venues/'
    | '/venues/$venueId/book'
    | '/account/bookings/'
    | '/account/saved/'
    | '/venues/$venueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  InfoSlugRoute: typeof InfoSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ListYourVenueIndexRoute: typeof ListYourVenueIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  VenuesVenueIdBookRoute: typeof VenuesVenueIdBookRoute
  AccountBookingsIndexRoute: typeof AccountBookingsIndexRoute
  AccountSavedIndexRoute: typeof AccountSavedIndexRoute
  VenuesVenueIdIndexRoute: typeof VenuesVenueIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$slug': {
      id: '/info/$slug'
      path: '/info/$slug'
      fullPath: '/info/$slug'
      preLoaderRoute: typeof InfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-venue/': {
      id: '/list-your-venue/'
      path: '/list-your-venue'
      fullPath: '/list-your-venue/'
      preLoaderRoute: typeof ListYourVenueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings/': {
      id: '/account/bookings/'
      path: '/account/bookings'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AccountBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/saved/': {
      id: '/account/saved/'
      path: '/account/saved'
      fullPath: '/account/saved/'
      preLoaderRoute: typeof AccountSavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId/': {
      id: '/venues/$venueId/'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId/'
      preLoaderRoute: typeof VenuesVenueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId/book': {
      id: '/venues/$venueId/book'
      path: '/venues/$venueId/book'
      fullPath: '/venues/$venueId/book'
      preLoaderRoute: typeof VenuesVenueIdBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  InfoSlugRoute: InfoSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ListYourVenueIndexRoute: ListYourVenueIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  VenuesVenueIdBookRoute: VenuesVenueIdBookRoute,
  AccountBookingsIndexRoute: AccountBookingsIndexRoute,
  AccountSavedIndexRoute: AccountSavedIndexRoute,
  VenuesVenueIdIndexRoute: VenuesVenueIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
